SRCS		+= $(NAME).c
OBJS		+= $(NAME).o $(WIN32RES)

$(MAPFILES):
	# The map files are generated by Perl scripts. We don't automatically
	# regenerate them here.

$(NAME).o: $(MAPFILES)

rpath =

all: all-shared-lib

include $(top_srcdir)/src/Makefile.shlib

install: all installdirs install-lib

installdirs: installdirs-lib

uninstall: uninstall-lib

clean distclean: clean-lib
	rm -f $(OBJS)
