#-------------------------------------------------------------------------
#
# src/backend/utils/mb/conversion_procs/utf8_and_iso8859/Makefile
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/utf8_and_iso8859
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global
mapfiledir = $(top_builddir)/src/backend/utils/mb/Unicode

NAME		= utf8_and_iso8859
PGFILEDESC	= "utf8 <-> iso8859 text conversions"
MAPFILES	= $(mapfiledir)/iso8859_10_to_utf8.map \
			  $(mapfiledir)/iso8859_13_to_utf8.map \
			  $(mapfiledir)/iso8859_14_to_utf8.map \
			  $(mapfiledir)/iso8859_15_to_utf8.map \
			  $(mapfiledir)/iso8859_16_to_utf8.map \
			  $(mapfiledir)/iso8859_2_to_utf8.map \
			  $(mapfiledir)/iso8859_3_to_utf8.map \
			  $(mapfiledir)/iso8859_4_to_utf8.map \
			  $(mapfiledir)/iso8859_5_to_utf8.map \
			  $(mapfiledir)/iso8859_6_to_utf8.map \
			  $(mapfiledir)/iso8859_7_to_utf8.map \
			  $(mapfiledir)/iso8859_8_to_utf8.map \
			  $(mapfiledir)/iso8859_9_to_utf8.map \
			  $(mapfiledir)/utf8_to_iso8859_10.map \
			  $(mapfiledir)/utf8_to_iso8859_13.map \
			  $(mapfiledir)/utf8_to_iso8859_14.map \
			  $(mapfiledir)/utf8_to_iso8859_15.map \
			  $(mapfiledir)/utf8_to_iso8859_16.map \
			  $(mapfiledir)/utf8_to_iso8859_2.map \
			  $(mapfiledir)/utf8_to_iso8859_3.map \
			  $(mapfiledir)/utf8_to_iso8859_4.map \
			  $(mapfiledir)/utf8_to_iso8859_5.map \
			  $(mapfiledir)/utf8_to_iso8859_6.map \
			  $(mapfiledir)/utf8_to_iso8859_7.map \
			  $(mapfiledir)/utf8_to_iso8859_8.map \
			  $(mapfiledir)/utf8_to_iso8859_9.map

include $(srcdir)/../proc.mk
