#!/usr/bin/perl

# Copyright (c) 2023, PostgreSQL Global Development Group

# script to detect compile time errors and warnings in all perl files

use strict;
use warnings;

use FindBin ();
use lib "$FindBin::Bin";

use Cwd qw(abs_path);
use FindPerlFiles;

die "No directories or files specified\n" unless @ARGV;

my $srcroot = abs_path("$FindBin::Bin/../../..");

my $includes="";

my @incdirs = qw(
    src/tools/msvc
    src/tools/msvc/dummylib
    src/backend/catalog
    src/test/perl
    src/backend/utils/mb/Unicode
    src/bin/pg_rewind src/test/ssl/t
);

foreach my $inc (@incdirs)
{
    $includes .= "-I $srcroot/$inc ";
}

my @files =  FindPerlFiles::findperl(@ARGV);

my $status = 0;

foreach my $file (@files)
{
    my $out = `perl $includes -cw $file 2>&1`;
    next if $out =~ /OK/;
    $status = 1;
    print $out;
}

exit $status;
