#!/bin/sh

# src/tools/perlcheck/pgperlcritic

test -f src/tools/perlcheck/perlcriticrc || {
	echo could not find src/tools/perlcheck/perlcriticrc
	exit 1
	}

set -e

# set this to override default perlcritic program:
PERLCRITIC=${PERLCRITIC:-perlcritic}

. src/tools/perlcheck/find_perl_files

flist=`mktemp`
find_perl_files > $flist

pattern='src/test/perl/|src/backend/catalog/Catalog.pm|src/tools/msvc/[^/]*.pm'

# normal sev 5 critic
egrep -v  "$pattern" < $flist | xargs $PERLCRITIC \
	  --quiet \
	  --program-extensions .pl \
	  --profile=src/tools/perlcheck/perlcriticrc

# more strict sev 3 critic for some library files
egrep  "$pattern" < $flist | xargs $PERLCRITIC --severity 3 \
	  --quiet \
	  --program-extensions .pl \
	  --profile=src/tools/perlcheck/perlcriticrc

rm -f $flist
