#!/usr/bin/perl

# Copyright (c) 2023, PostgreSQL Global Development Group

# src/tools/perlcheck/pgperlcritic

use strict;
use warnings;

use FindBin ();
use lib "$FindBin::Bin";
use FindPerlFiles;

die "No directories or files specified\n" unless @ARGV;

my $rc_loc = "$FindBin::Bin/perlcriticrc";

die "no $rc_loc\n" unless -f $rc_loc;

# set this to override default perlcritic program:
my $perlcritic = $ENV{PERLCRITIC} || 'perlcritic';

my @files = FindPerlFiles::findperl(@ARGV);

exit unless @files;

exec $perlcritic, '--program-extensions',  '.pl', "--profile=$rc_loc", @files
