#!/usr/bin/perl
#
# Generate the list of configuration parameter names for the
# "PostgreSQL Parameters" appendix.
#
# Every configuration parameter is documented in config.sgml inside a
# <varlistentry> whose id starts with "guc-".  The parameter name is taken from
# the <varname> at the start of the <term>, and the entry id is used to link
# each name to its detailed description.  Entries that merely describe possible
# values of a parameter (such as the HIGH/MEDIUM groups of ssl_ciphers) use a
# <literal> term instead of a <varname> and are therefore skipped.
#
# Copyright (c) 2026, PostgreSQL Global Development Group

use strict;
use warnings FATAL => 'all';

my $configfile = $ARGV[0];

open my $fh, '<', $configfile or die "could not open $configfile: $!";
my $content = do { local $/; <$fh> };
close $fh;

my %ids;

# Match each parameter (varlistentry tag) and capture the id and the varname.
while ($content =~
	m{<varlistentry\s+id="(guc-[^"]*)"[^>]*>\s*<term>\s*<varname>([^<]+)</varname>}sg
	)
{
	$ids{$2} = $1;
}

print "<!-- autogenerated by generate-guc-list.pl, do not edit -->\n";
print "<simplelist>\n";
# Sort case-insensitively so that mixed-case names (such as DateStyle) are
# ordered by their letters rather than by ASCII case.
foreach my $name (sort { lc($a) cmp lc($b) } keys %ids)
{
	print
	  " <member><link linkend=\"$ids{$name}\"><varname>$name</varname></link></member>\n";
}
print "</simplelist>\n";
