#!/usr/bin/perl
#
# Generate table of Unicode normalization "quick check" properties
# (see UAX #15).  Pass DerivedNormalizationProps.txt as argument.  The
# output is on stdout.
#
# Copyright (c) 2020-2025, PostgreSQL Global Development Group

use strict;
use warnings FATAL => 'all';

use FindBin;
use lib "$FindBin::RealBin/../../tools/";
use PerfectHash;

my %data;

print
  "/* generated by src/common/unicode/generate-unicode_normprops_table.pl, do not edit */\n\n";

print <<EOS;
#include "common/unicode_norm.h"

/*
 * Normalization quick check entry for codepoint.
 */
enum
{
	UNICODE_QC_MAYBE = 0x03
};
EOS

foreach my $line (<ARGV>)
{
	chomp $line;
	$line =~ s/\s*#.*$//;
	next if $line eq '';
	my ($codepoint, $prop, $value) = split /\s*;\s*/, $line;
	next if $prop !~ /_QC/;

	my ($first, $last);
	if ($codepoint =~ /\.\./)
	{
		($first, $last) = split /\.\./, $codepoint;
	}
	else
	{
		$first = $last = $codepoint;
	}

	foreach my $cp (hex($first) .. hex($last))
	{
		$data{$prop}{$cp} = $value;
	}
}

# We create a separate array for each normalization form rather than,
# say, a two-dimensional array, because that array would be very
# sparse and would create unnecessary overhead especially for the NFC
# lookup.
foreach my $prop (sort keys %data)
{
	# Don't build the tables for the "D" forms because they are too
	# big.  See also unicode_is_normalized_quickcheck().
	next if $prop eq "NFD_QC" || $prop eq "NFKD_QC";

	my %subdata = %{ $data{$prop} };
	my @cp_packed;
	my @uint8;
	my @codepoints = sort { $a <=> $b } keys %subdata;
	foreach my $cp (@codepoints)
	{
		my $qc;
		if ($subdata{$cp} eq 'N')
		{
			# According to the specification, NO = 0.
			# Temporarily set NO to 0x01. According to the code, this will be
			# converted to 0x00.
			$qc = 0x01;
		}
		elsif ($subdata{$cp} eq 'M')
		{
			# According to the specification, MAYBE should be equal to -1.
			# We cannot store this value in the first two bits. Therefore,
			# in our table, MAYBE = 0x03 (the first two bits are raised).
			$qc = 0x03;
		}
		else
		{
			die;
		}

		# Determine the byte index and bit position in that byte.
		# Each code point occupies 2 bits, as there are only two possible
		# values ('N' and 'M').
		my $index = ($cp * 2) / 8;
		my $bit = ($cp * 2) % 8;

		# Set the required 2 bits to the desired position.
		$uint8[$index] = 0 unless exists $uint8[$index];
		$uint8[$index] |= $qc << $bit;
	}

	my $length = scalar @uint8;
	my $min = sprintf("0x%06X", $codepoints[0]);
	my $max = sprintf("0x%06X", $codepoints[-1]);

	# Print an enum declaration defining the range boundaries for each forms.
	print "\nenum\n";
	print "{\n";
	print "	UNICODE_${prop}_MIN = $min,\n";
	print "	UNICODE_${prop}_MAX = $max\n";
	print "};\n";

	print "\n";
	print "static const uint8 UnicodeNormProps_${prop}[$length] = {\n\t";

	foreach my $idx (0 .. $#uint8)
	{
		my $value = $uint8[$idx];
		$value = 0x00 unless defined $value;

		# If the value is not shown in the table, it is equal to YES = 1.
		# We go through the even bits (4 in total in each value) and change
		# 0x00 to 0x01 (YES), 0x01 to 0x00 (NO).
		foreach my $pos (0 .. 3)
		{
			my $bit = $pos * 2;
			my $val = $value >> $bit;

			$val &= ~(((2**8) - 1) << 2);

			if ($val == 0x00)
			{
				$value |= 1 << $bit;
			}
			elsif ($val == 0x01)
			{
				$value &= ~(1 << $bit);
			}
		}

		print $value;

		if ($idx == $#uint8)
		{
			print "\n";
			last;
		}

		print(($idx + 1) % 15 ? ", " : ",\n\t");
	}

	print "};\n";
}
