#!/usr/bin/perl
#
# Generate the sqlstate_names.h header from errcodes.txt
# Copyright (c) 2000-2026, PostgreSQL Global Development Group

use strict;
use warnings FATAL => 'all';
use Getopt::Long;

my $outfile = '';

GetOptions('outfile=s' => \$outfile) or die "$0: wrong arguments";

open my $errcodes, '<', $ARGV[0]
  or die "$0: could not open input file '$ARGV[0]': $!\n";

my $outfh;
if ($outfile)
{
	open $outfh, '>', $outfile
	  or die "$0: could not open output file '$outfile': $!\n";
}
else
{
	$outfh = *STDOUT;
}

my @entries;

while (<$errcodes>)
{
	chomp;

	# Skip comments and empty lines
	next if /^#/;
	next if /^\s*$/;

	# Skip section headers
	next if /^Section:/;

	die "unable to parse errcodes.txt"
	  unless /^([^\s]{5})\s+[EWS]\s+([^\s]+)/;

	push @entries, [$1, $2];
}

close $errcodes;

# Sort by SQLSTATE
@entries = sort { $a->[0] cmp $b->[0] } @entries;

print $outfh <<'HEADER';
/* autogenerated from src/backend/utils/errcodes.txt, do not edit */
#ifndef SQLSTATE_NAMES_H
#define SQLSTATE_NAMES_H

#include <string.h>

typedef struct
{
	const char sqlstate[6];
	const char *symbolic_name;
} SqlstateNameEntry;

static const SqlstateNameEntry sqlstate_name_table[] = {
HEADER

for my $e (@entries)
{
	print $outfh "\t{\"$e->[0]\", \"$e->[1]\"},\n";
}

print $outfh <<'FOOTER';
};

static inline const char *
sqlstate_to_symbolic_name(const char *sqlstate)
{
	int			lo = 0;
	int			hi = sizeof(sqlstate_name_table) / sizeof(sqlstate_name_table[0]) - 1;

	while (lo <= hi)
	{
		int			mid = (lo + hi) / 2;
		int			cmp = strncmp(sqlstate, sqlstate_name_table[mid].sqlstate, 5);

		if (cmp < 0)
			hi = mid - 1;
		else if (cmp > 0)
			lo = mid + 1;
		else
			return sqlstate_name_table[mid].symbolic_name;
	}
	return NULL;
}

#endif							/* SQLSTATE_NAMES_H */
FOOTER

close $outfh if ($outfile);
