#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/conveyor
#
# IDENTIFICATION
#    src/backend/access/conveyor/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/conveyor
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	cbcache.o \
	cbfsmpage.o \
	cbindexpage.o \
	cbmetapage.o \
	cbmodify.o \
	cbxlog.o \
	conveyor.o

include $(top_srcdir)/src/backend/common.mk
