#!/usr/bin/perl

# Copyright (c) 2023, PostgreSQL Global Development Group

# src/tools/pgindent/pgperltidy

use strict;
use warnings;

use FindBin ();
use lib "$FindBin::Bin/../perlcheck";
use FindPerlFiles;

my $perltidy = $ENV{PERLTIDY} || 'perltidy';

die "No directories or files specified\n" unless @ARGV;

my @files = FindPerlFiles::findperl(@ARGV);

exit unless @files;

exec "$perltidy", "--profile=$FindBin::Bin /perltidyrc", @files;
