#!/bin/sh

# Check (almost) all PostgreSQL include files for standalone build.
#
# Argument 1 is the top-level source directory, argument 2 the
# top-level build directory (they might be the same). If not set, they
# default to the current directory.
#
# Needs to be run after configuring and creating all generated headers.
# It's advisable to configure --with-perl --with-python, else you're
# likely to get errors from associated headers.
#
# No output if everything is OK, else compiler errors.
#
# src/tools/pginclude/headerscheck
# Copyright (c) 2009-2026, PostgreSQL Global Development Group

# option to check for C++ compatibility
if [ "$1" = "--cplusplus" ]; then
	cplusplus=true
	shift
else
	cplusplus=false
fi

if [ -z "$1" ]; then
    srcdir="."
else
    srcdir="$1"
fi

if [ -z "$2" ]; then
    builddir="."
else
    builddir="$2"
fi

me=`basename $0`

mydir=`dirname $0`
skipfile="$mydir/headerscheck_skip"

# Load the skip list into shell variables.
# We build a newline-separated list of paths to skip.
skip_all=""
skip_c_only=""
skip_cxx_only=""
while IFS= read -r line; do
    line=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
    case "$line" in
        ''|'#'*) continue ;;
    esac
    case "$line" in
        c_only:*)
            path=$(echo "$line" | sed 's/^c_only:[[:space:]]*//')
            skip_c_only="$skip_c_only
$path"
            ;;
        cxx_only:*)
            path=$(echo "$line" | sed 's/^cxx_only:[[:space:]]*//')
            skip_cxx_only="$skip_cxx_only
$path"
            ;;
        *)
            skip_all="$skip_all
$line"
            ;;
    esac
done < "$skipfile"

should_skip() {
    _path="$1"

    case "$skip_all" in
        *"$_path"*) return 0 ;;
    esac

    if $cplusplus; then
        case "$skip_cxx_only" in
            *"$_path"*) return 0 ;;
        esac
    else
        case "$skip_c_only" in
            *"$_path"*) return 0 ;;
        esac
    fi

    return 1
}

# These switches are g++ specific, you may override if necessary.
CXXFLAGS=${CXXFLAGS:- -fsyntax-only -Wall}

# Pull some info from configure's results.
MGLOB="$builddir/src/Makefile.global"
CPPFLAGS=`sed -n 's/^CPPFLAGS[ 	]*=[ 	]*//p' "$MGLOB"`
CFLAGS=`sed -n 's/^CFLAGS[ 	]*=[ 	]*//p' "$MGLOB"`
ICU_CFLAGS=`sed -n 's/^ICU_CFLAGS[ 	]*=[ 	]*//p' "$MGLOB"`
LLVM_CPPFLAGS=`sed -n 's/^LLVM_CPPFLAGS[ 	]*=[ 	]*//p' "$MGLOB"`
CC=`sed -n 's/^CC[ 	]*=[ 	]*//p' "$MGLOB"`
CXX=`sed -n 's/^CXX[ 	]*=[ 	]*//p' "$MGLOB"`
PG_SYSROOT=`sed -n 's/^PG_SYSROOT[ 	]*=[ 	]*//p' "$MGLOB"`
perl_includespec=`sed -n 's/^perl_includespec[ 	]*=[ 	]*//p' "$MGLOB"`
python_includespec=`sed -n 's/^python_includespec[ 	]*=[ 	]*//p' "$MGLOB"`

# needed on Darwin
CPPFLAGS=`echo "$CPPFLAGS" | sed "s|\\\$(PG_SYSROOT)|$PG_SYSROOT|g"`

# (EXTRAFLAGS is not set here, but user can pass it in if need be.)

if $cplusplus; then
	ext=cpp
	COMPILER=${CXX:-g++}
	# Extract any -I and -D switches from CPPFLAGS.
	for flag in $CPPFLAGS; do
	  case $flag in
	    -I*|-D*) CXXPPFLAGS="$CXXPPFLAGS $flag";;
	  esac
	done
	COMPILER_FLAGS="$CXXPPFLAGS $CXXFLAGS $ICU_CFLAGS $LLVM_CPPFLAGS"
else
	ext=c
	COMPILER=${CC:-gcc}
	COMPILER_FLAGS="$CPPFLAGS $CFLAGS $ICU_CFLAGS $LLVM_CPPFLAGS"
fi

# Create temp directory.  Help ccache by using a stable name.  Include
# extension to allow running C and C++ checks in parallel.
tmp="tmp_${me}_${ext}"
mkdir -p "$tmp"

trap "ret=$?; rm -rf $tmp; exit $ret" 0 1 2 3 15

exit_status=0

# Scan all of src/ and contrib/ for header files.
for f in `cd "$srcdir" && find src contrib -name '*.h' -print`
do
	# Check the shared skip list
	if should_skip "$f"; then
		continue
	fi

	# Help ccache by using a stable name.  Remove slashes and dots.
	test_file_name=$(printf '%s' "$f" | tr '/.' '__')

	# OK, create .c file to include this .h file.
	{
	    $cplusplus && echo 'extern "C" {'
	    # Ideally we'd pre-include only the appropriate one of
	    # postgres.h, postgres_fe.h, or c.h.  We don't always have enough
	    # info to guess which, but in some subdirectories there's a
	    # reasonable choice to make, and otherwise we use postgres.h.
	    # Also, those three files should compile with no pre-include, as
	    # should src/interfaces headers meant to be exposed to clients.
	    case "$f" in
		src/include/postgres.h) ;;
		src/include/postgres_fe.h) ;;
		src/include/c.h) ;;
		src/interfaces/libpq/libpq-fe.h) ;;
		src/interfaces/libpq/libpq-events.h) ;;
		src/interfaces/ecpg/ecpglib/ecpglib_extern.h)
		    echo '#include "postgres_fe.h"' ;;
		src/interfaces/ecpg/ecpglib/*) ;;
		src/interfaces/*)
		    echo '#include "postgres_fe.h"' ;;
		src/bin/*)
		    echo '#include "postgres_fe.h"' ;;
		src/fe_utils/*)
		    echo '#include "postgres_fe.h"' ;;
		src/port/*) ;;
		src/common/*)
		    echo '#include "c.h"' ;;
		*)
		    echo '#include "postgres.h"' ;;
	    esac
	    echo "#include \"$f\""
	    $cplusplus && echo '};'
	} >$tmp/$test_file_name.$ext

	# Some subdirectories need extra -I switches.
	case "$f" in
	    src/pl/plperl/*)
		EXTRAINCLUDES="$perl_includespec" ;;
	    src/pl/plpython/*)
		EXTRAINCLUDES="$python_includespec" ;;
	    src/interfaces/ecpg/*)
		EXTRAINCLUDES="-I $builddir/src/interfaces/ecpg/include -I $srcdir/src/interfaces/ecpg/include" ;;
	    src/backend/parser/*)
		EXTRAINCLUDES="-I $builddir/src/backend/parser/" ;;
	    src/backend/utils/adt/*)
		EXTRAINCLUDES="-I $builddir/src/backend/utils/adt/" ;;
	    *)
		EXTRAINCLUDES="" ;;
	esac

	# Run the test.
	if ! $COMPILER $COMPILER_FLAGS -I $builddir -I $srcdir \
		-I $builddir/src/include -I $srcdir/src/include \
		-I $builddir/src/interfaces/libpq -I $srcdir/src/interfaces/libpq \
		$EXTRAINCLUDES $EXTRAFLAGS -c "$tmp/$test_file_name.$ext" -o "$tmp/$test_file_name.o"
	then
		exit_status=1
	fi

	rm -f "$tmp/$test_file_name.$ext" "$tmp/$test_file_name.o"
done

exit $exit_status
