# env var name to use in place of LD_LIBRARY_PATH
ld_library_path_var = DYLD_LIBRARY_PATH

# Rule for building a shared library from a single .o file
%$(DLSUFFIX): %.o
	$(CC) $(CFLAGS) $< $(LDFLAGS) $(LDFLAGS_SL) -dynamiclib -Wl,-undefined,dynamic_lookup -o $@
