--
-- pg_get_table_ddl
--
-- All tests pass owner=>false so the ALTER TABLE OWNER TO line is not
-- emitted, keeping output stable across test runners (which may run under
-- different role names).
--
CREATE SCHEMA pgtbl_ddl_test;
SET search_path = pgtbl_ddl_test;

-- Basic table with PRIMARY KEY, NOT NULL, DEFAULT, COLLATE.
CREATE TABLE basic (
    id int PRIMARY KEY,
    name text NOT NULL DEFAULT 'anon' COLLATE "C"
);
SELECT * FROM pg_get_table_ddl('basic'::regclass, 'owner', 'false');

-- Identity columns (with default and custom sequence options).
CREATE TABLE id_cols (
    id_always int GENERATED ALWAYS AS IDENTITY,
    id_default int GENERATED BY DEFAULT AS IDENTITY
);
SELECT * FROM pg_get_table_ddl('id_cols'::regclass, 'owner', 'false');

CREATE TABLE id_custom (
    v int GENERATED ALWAYS AS IDENTITY (
        SEQUENCE NAME id_custom_v_seq
        START WITH 100 INCREMENT BY 5
        MINVALUE 50 MAXVALUE 1000
        CACHE 10 CYCLE
    )
);
SELECT * FROM pg_get_table_ddl('id_custom'::regclass, 'owner', 'false');

-- Generated stored column.
CREATE TABLE gen_cols (
    cents int,
    dollars numeric GENERATED ALWAYS AS (cents / 100.0) STORED
);
SELECT * FROM pg_get_table_ddl('gen_cols'::regclass, 'owner', 'false');

-- STORAGE and COMPRESSION (only emitted when non-default for the type).
CREATE TABLE storage_cols (
    a text STORAGE EXTERNAL,
    b text STORAGE MAIN,
    c text COMPRESSION pglz
);
SELECT * FROM pg_get_table_ddl('storage_cols'::regclass, 'owner', 'false');

-- Constraints: CHECK, UNIQUE, FOREIGN KEY (DEFERRABLE).
CREATE TABLE refd (id int PRIMARY KEY);
CREATE TABLE cons (
    a int CHECK (a > 0),
    b int UNIQUE,
    c int REFERENCES refd(id) DEFERRABLE INITIALLY DEFERRED
);
SELECT * FROM pg_get_table_ddl('cons'::regclass, 'owner', 'false');

-- Indexes: functional and partial.  Constraint-backing indexes are
-- suppressed (they are emitted by the constraint loop).
CREATE TABLE idxd (id int PRIMARY KEY, name text);
CREATE INDEX idxd_lower ON idxd (lower(name));
CREATE INDEX idxd_partial ON idxd (id) WHERE id > 100;
SELECT * FROM pg_get_table_ddl('idxd'::regclass, 'owner', 'false');

-- Inheritance, including a child DEFAULT override on an inherited column.
CREATE TABLE par (a int DEFAULT 1, b text);
CREATE TABLE ch (c int) INHERITS (par);
ALTER TABLE ch ALTER COLUMN a SET DEFAULT 999;
SELECT * FROM pg_get_table_ddl('ch'::regclass, 'owner', 'false');

-- Per-column attoptions: emitted as ALTER COLUMN SET (...).
CREATE TABLE attopt (a int, b text);
ALTER TABLE attopt ALTER COLUMN a SET (n_distinct = 100);
SELECT * FROM pg_get_table_ddl('attopt'::regclass, 'owner', 'false');

-- Partitioned table parent (RANGE and HASH).
CREATE TABLE parted_range (id int, k int) PARTITION BY RANGE (id);
SELECT * FROM pg_get_table_ddl('parted_range'::regclass, 'owner', 'false');

CREATE TABLE parted_hash (id int) PARTITION BY HASH (id);
SELECT * FROM pg_get_table_ddl('parted_hash'::regclass, 'owner', 'false');

-- Partition children: FROM/TO, WITH (modulus, remainder), DEFAULT.
CREATE TABLE parted_range_1 PARTITION OF parted_range
    FOR VALUES FROM (0) TO (100);
ALTER TABLE parted_range_1 ALTER COLUMN k SET DEFAULT 7;
SELECT * FROM pg_get_table_ddl('parted_range_1'::regclass, 'owner', 'false');

CREATE TABLE parted_hash_0 PARTITION OF parted_hash
    FOR VALUES WITH (modulus 2, remainder 0);
SELECT * FROM pg_get_table_ddl('parted_hash_0'::regclass, 'owner', 'false');

CREATE TABLE parted_range_def PARTITION OF parted_range DEFAULT;
SELECT * FROM pg_get_table_ddl('parted_range_def'::regclass, 'owner', 'false');

-- Rules.
CREATE TABLE rt (id int);
CREATE TABLE rt_log (id int);
CREATE RULE rt_log_insert AS ON INSERT TO rt
    DO ALSO INSERT INTO rt_log VALUES (NEW.id);
SELECT * FROM pg_get_table_ddl('rt'::regclass, 'owner', 'false');

-- Extended statistics.
CREATE TABLE stx (a int, b int, c int);
CREATE STATISTICS stx_ndv (ndistinct) ON a, b FROM stx;
SELECT * FROM pg_get_table_ddl('stx'::regclass, 'owner', 'false');

-- Row-level security toggles.
CREATE TABLE rls (id int);
ALTER TABLE rls ENABLE ROW LEVEL SECURITY;
ALTER TABLE rls FORCE ROW LEVEL SECURITY;
SELECT * FROM pg_get_table_ddl('rls'::regclass, 'owner', 'false');

-- REPLICA IDENTITY: emitted only when not the default.
CREATE TABLE ri_full (a int);
ALTER TABLE ri_full REPLICA IDENTITY FULL;
SELECT * FROM pg_get_table_ddl('ri_full'::regclass, 'owner', 'false');

CREATE TABLE ri_idx (a int NOT NULL);
CREATE UNIQUE INDEX ri_idx_a ON ri_idx (a);
ALTER TABLE ri_idx REPLICA IDENTITY USING INDEX ri_idx_a;
SELECT * FROM pg_get_table_ddl('ri_idx'::regclass, 'owner', 'false');

-- UNLOGGED + reloptions.
CREATE UNLOGGED TABLE uno (id int) WITH (fillfactor = 70);
SELECT * FROM pg_get_table_ddl('uno'::regclass, 'owner', 'false');

-- Typed table (CREATE TABLE OF type_name).  Columns inherited from the
-- type emit nothing; locally-applied DEFAULT, NOT NULL and CHECK come
-- out through a single "(col WITH OPTIONS ...)" list.
CREATE TYPE typed_t AS (a int, b text);
CREATE TABLE typed_plain OF typed_t;
SELECT * FROM pg_get_table_ddl('typed_plain'::regclass, 'owner', 'false');

CREATE TABLE typed_over OF typed_t (
    a WITH OPTIONS DEFAULT 7 NOT NULL,
    b WITH OPTIONS NOT NULL,
    CONSTRAINT b_nonempty CHECK (length(b) > 0)
);
SELECT * FROM pg_get_table_ddl('typed_over'::regclass, 'owner', 'false');

-- Temporary tables + ON COMMIT.  Temp tables live in a session-local
-- namespace whose name varies between runs, so we strip the schema
-- prefix.  ON COMMIT DROP only fires at commit, so the queries that
-- need to see the catalog entry must run in the same transaction as
-- the CREATE.
BEGIN;
CREATE TEMP TABLE temp_default (id int);
CREATE TEMP TABLE temp_delete (id int) ON COMMIT DELETE ROWS;
CREATE TEMP TABLE temp_drop (id int) ON COMMIT DROP;

SELECT regexp_replace(line, '"?pg_temp_?[0-9]+"?\.', 'pg_temp.') AS line
FROM pg_get_table_ddl('temp_default'::regclass, 'owner', 'false') AS line
WHERE line LIKE 'CREATE %';

SELECT regexp_replace(line, '"?pg_temp_?[0-9]+"?\.', 'pg_temp.') AS line
FROM pg_get_table_ddl('temp_delete'::regclass, 'owner', 'false') AS line
WHERE line LIKE 'CREATE %';

SELECT regexp_replace(line, '"?pg_temp_?[0-9]+"?\.', 'pg_temp.') AS line
FROM pg_get_table_ddl('temp_drop'::regclass, 'owner', 'false') AS line
WHERE line LIKE 'CREATE %';
ROLLBACK;

-- Pretty mode.
SELECT * FROM pg_get_table_ddl('basic'::regclass, 'owner', 'false', 'pretty', 'true');

-- includes_* gating: each sub-object category can be suppressed individually.
-- includes_indexes=false hides the CREATE INDEX statements.
SELECT * FROM pg_get_table_ddl('idxd'::regclass, 'owner', 'false',
                               'includes_indexes', 'false');

-- includes_constraints=false hides both inline CHECK in CREATE TABLE and
-- the ALTER TABLE ... ADD CONSTRAINT lines.
SELECT * FROM pg_get_table_ddl('cons'::regclass, 'owner', 'false',
                               'includes_constraints', 'false');

-- includes_rules=false hides the CREATE RULE.
SELECT * FROM pg_get_table_ddl('rt'::regclass, 'owner', 'false',
                               'includes_rules', 'false');

-- includes_statistics=false hides the CREATE STATISTICS.
SELECT * FROM pg_get_table_ddl('stx'::regclass, 'owner', 'false',
                               'includes_statistics', 'false');

-- includes_rls=false hides the ENABLE/FORCE ROW LEVEL SECURITY toggles.
SELECT * FROM pg_get_table_ddl('rls'::regclass, 'owner', 'false',
                               'includes_rls', 'false');

-- includes_replica_identity=false hides the REPLICA IDENTITY clause.
SELECT * FROM pg_get_table_ddl('ri_full'::regclass, 'owner', 'false',
                               'includes_replica_identity', 'false');

-- includes_partition: default is false, so the partitioned-table parent
-- DDL on its own does not include its children.  Setting it to true
-- appends the children's DDL after the parent.
SELECT * FROM pg_get_table_ddl('parted_range'::regclass, 'owner', 'false',
                               'includes_partition', 'true');

-- Error: not an ordinary or partitioned table.
CREATE VIEW v AS SELECT 1 AS x;
SELECT * FROM pg_get_table_ddl('v'::regclass);

CREATE SEQUENCE s;
SELECT * FROM pg_get_table_ddl('s'::regclass);

-- NULL argument returns no rows.
SELECT * FROM pg_get_table_ddl(NULL);

-- Unrecognized option.
SELECT * FROM pg_get_table_ddl('basic'::regclass, 'bogus', 'true');

-- Odd number of variadic args.
SELECT * FROM pg_get_table_ddl('basic'::regclass, 'pretty');

-- Round-trip verification.  For every test table, capture the DDL the
-- function emits, drop the schema, replay each table's DDL in
-- dependency order, and confirm that pg_get_table_ddl on the recreated
-- relation matches the original line-for-line.  The final SELECT must
-- return zero rows.
CREATE TEMP TABLE pgtbl_ddl_rt_orig (name text, ord int, line text);
INSERT INTO pgtbl_ddl_rt_orig
SELECT t.name, o.ord, o.line
FROM (VALUES
        ('basic'), ('id_cols'), ('id_custom'), ('gen_cols'), ('storage_cols'),
        ('refd'), ('cons'), ('idxd'),
        ('par'), ('ch'), ('attopt'),
        ('parted_range'), ('parted_range_1'), ('parted_range_def'),
        ('parted_hash'), ('parted_hash_0'),
        ('rt_log'), ('rt'),
        ('stx'), ('rls'), ('ri_full'), ('ri_idx'), ('uno')
     ) AS t(name),
     LATERAL pg_get_table_ddl(('pgtbl_ddl_test.' || t.name)::regclass,
                              'owner', 'false') WITH ORDINALITY o(line, ord);

DO $$
DECLARE
    tables CONSTANT text[] := ARRAY[
        'basic', 'id_cols', 'id_custom', 'gen_cols', 'storage_cols',
        'refd', 'cons', 'idxd',
        'par', 'ch', 'attopt',
        'parted_range', 'parted_range_1', 'parted_range_def',
        'parted_hash', 'parted_hash_0',
        'rt_log', 'rt',
        'stx', 'rls', 'ri_full', 'ri_idx', 'uno'
    ];
    t text;
    stmt text;
BEGIN
    DROP SCHEMA pgtbl_ddl_test CASCADE;
    CREATE SCHEMA pgtbl_ddl_test;
    FOREACH t IN ARRAY tables LOOP
        FOR stmt IN
            SELECT line FROM pgtbl_ddl_rt_orig WHERE name = t ORDER BY ord
        LOOP
            EXECUTE stmt;
        END LOOP;
    END LOOP;
END $$;

WITH after_ddl AS (
    SELECT t.name, o.ord, o.line
    FROM (SELECT DISTINCT name FROM pgtbl_ddl_rt_orig) AS t,
         LATERAL pg_get_table_ddl(('pgtbl_ddl_test.' || t.name)::regclass,
                                  'owner', 'false') WITH ORDINALITY o(line, ord)
)
(SELECT 'missing-in-copy' AS kind, name, ord, line FROM pgtbl_ddl_rt_orig
 EXCEPT
 SELECT 'missing-in-copy', name, ord, line FROM after_ddl)
UNION ALL
(SELECT 'extra-in-copy' AS kind, name, ord, line FROM after_ddl
 EXCEPT
 SELECT 'extra-in-copy', name, ord, line FROM pgtbl_ddl_rt_orig)
ORDER BY kind, name, ord;

-- Cleanup.
DROP SCHEMA pgtbl_ddl_test CASCADE;
