name: hackorum patch CI
on: push
jobs:
  ci:
    uses: hackorum-dev/postgres-ci/.github/workflows/patch-ci.yml@main
    permissions:
      contents: write
      packages: write
    with:
      pg_major: 10
      topic_id: 36172
      message_index: 9
      base_sha: 42fcad68a9c0e0ebecf6842888723cad1f9d5be2
